### ISSUE TITLE
not updating ?

### ISSUE THREAD

**Issue by jonnytest1** [alejandroSuch/angular-cli#25]
apparently the image is not updating served content oO

**Comment by alejandroSuch** [comment]
Which version are you working on? On this trace, you can see two updates. Tested on my chrome and websocket was working properly:

```
$ docker run -it --rm -w /app -v $(pwd):/app -p 4200:4200 alexsuch/angular-cli:1.6.6-chromium ng serve --host 0.0.0.0
** NG Live Development Server is listening on 0.0.0.0:4200, open your browser on http://localhost:4200/ **
Date: 2018-02-20T10:54:29.057Z                                                          
Hash: 62da4241666a93276bd7
Time: 43470ms
chunk {inline} inline.bundle.js (inline) 5.79 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 19 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 546 kB [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 33.4 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 7.43 MB [initial] [rendered]

webpack: Compiled successfully.
webpack: Compiling...
Date: 2018-02-20T10:55:26.029Z - Hash: e5589579ec7338239760 - Time: 928ms          
4 unchanged chunks
chunk {main} main.bundle.js (main) 19 kB [initial] [rendered]

webpack: Compiled successfully.
webpack: Compiling...
Date: 2018-02-20T10:55:47.578Z - Hash: 177409ad717f00dd7011 - Time: 767ms          
5 unchanged chunks

webpack: Compiled successfully.
webpack: Compiling...
Date: 2018-02-20T10:56:00.102Z - Hash: 7d5f805d18684d22142e - Time: 742ms          
4 unchanged chunks
chunk {main} main.bundle.js (main) 18.9 kB [initial] [rendered]

webpack: Compiled successfully.
```

**Comment by jonnytest1** [comment]
even the auto redeploy after an edit of the source code ?


Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Alejandro Such <notifications@github.com> Datum: 20.02.18  11:56  (GMT+01:00) An: alejandroSuch/angular-cli <angular-cli@noreply.github.com> Cc: jonnytest1 <ga86lad@mytum.de>, Author <author@noreply.github.com> Betreff: Re: [alejandroSuch/angular-cli] not updating ? (#25) 
Which version are you working on? On this trace, you can see two updates. Tested on my chrome and websocket was working properly:
$ docker run -it --rm -w /app -v $(pwd):/app -p 4200:4200 alexsuch/angular-cli:1.6.6-chromium ng serve --host 0.0.0.0
** NG Live Development Server is listening on 0.0.0.0:4200, open your browser on http://localhost:4200/ **
Date: 2018-02-20T10:54:29.057Z                                                          
Hash: 62da4241666a93276bd7
Time: 43470ms
chunk {inline} inline.bundle.js (inline) 5.79 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 19 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 546 kB [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 33.4 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 7.43 MB [initial] [rendered]

webpack: Compiled successfully.
webpack: Compiling...
Date: 2018-02-20T10:55:26.029Z - Hash: e5589579ec7338239760 - Time: 928ms          
4 unchanged chunks
chunk {main} main.bundle.js (main) 19 kB [initial] [rendered]

webpack: Compiled successfully.
webpack: Compiling...
Date: 2018-02-20T10:55:47.578Z - Hash: 177409ad717f00dd7011 - Time: 767ms          
5 unchanged chunks

webpack: Compiled successfully.
webpack: Compiling...
Date: 2018-02-20T10:56:00.102Z - Hash: 7d5f805d18684d22142e - Time: 742ms          
4 unchanged chunks
chunk {main} main.bundle.js (main) 18.9 kB [initial] [rendered]

webpack: Compiled successfully.


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/alejandroSuch/angular-cli","title":"alejandroSuch/angular-cli","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/alejandroSuch/angular-cli"}},"updates":{"snippets":[{"icon":"PERSON","message":"@alejandroSuch in #25: Which version are you working on? On this trace, you can see two updates. Tested on my chrome and websocket was working properly:\r\n\r\n```\r\n$ docker run -it --rm -w /app -v $(pwd):/app -p 4200:4200 alexsuch/angular-cli:1.6.6-chromium ng serve --host 0.0.0.0\r\n** NG Live Development Server is listening on 0.0.0.0:4200, open your browser on http://localhost:4200/ **\r\nDate: 2018-02-20T10:54:29.057Z                                                          \r\nHash: 62da4241666a93276bd7\r\nTime: 43470ms\r\nchunk {inline} inline.bundle.js (inline) 5.79 kB [entry] [rendered]\r\nchunk {main} main.bundle.js (main) 19 kB [initial] [rendered]\r\nchunk {polyfills} polyfills.bundle.js (polyfills) 546 kB [initial] [rendered]\r\nchunk {styles} styles.bundle.js (styles) 33.4 kB [initial] [rendered]\r\nchunk {vendor} vendor.bundle.js (vendor) 7.43 MB [initial] [rendered]\r\n\r\nwebpack: Compiled successfully.\r\nwebpack: Compiling...\r\nDate: 2018-02-20T10:55:26.029Z - Hash: e5589579ec7338239760 - Time: 928ms          \r\n4 unchanged chunks\r\nchunk {main} main.bundle.js (main) 19 kB [initial] [rendered]\r\n\r\nwebpack: Compiled successfully.\r\nwebpack: Compiling...\r\nDate: 2018-02-20T10:55:47.578Z - Hash: 177409ad717f00dd7011 - Time: 767ms          \r\n5 unchanged chunks\r\n\r\nwebpack: Compiled successfully.\r\nwebpack: Compiling...\r\nDate: 2018-02-20T10:56:00.102Z - Hash: 7d5f805d18684d22142e - Time: 742ms          \r\n4 unchanged chunks\r\nchunk {main} main.bundle.js (main) 18.9 kB [initial] [rendered]\r\n\r\nwebpack: Compiled successfully.\r\n```"}],"action":{"name":"View Issue","url":"https://github.com/alejandroSuch/angular-cli/issues/25#issuecomment-366941190"}}}

**Comment by alejandroSuch** [comment]
Yes! All those `webpack: Compiling...` messages you see have occured after editing a file.

Which version of the docker image are you using? Does it happen with all of them?

**Comment by alejandroSuch** [comment]
@jonnytest1 did it work? should I close this issue?
