### ISSUE TITLE
Bad version of @angular/cli for tag v1.7.0

### ISSUE THREAD

**Issue by zralock** [alejandroSuch/angular-cli#26]
Tag `v1.7.0` is pointing to commit https://github.com/alejandroSuch/angular-cli/commit/657c634f2167b57acd9a51b6555c03ab4956e3ad with `@angular/cli@v1.5.5` instead of https://github.com/alejandroSuch/angular-cli/commit/aed8f13db01e7add76e2ec05afe92617f8839a61

**Comment by alejandroSuch** [comment]
Fixed!

Thanks a lot @zralock
