### ISSUE TITLE
6.1.2-chromium tag is using an out of date version of Node

### ISSUE THREAD

**Issue by garunski** [alejandroSuch/angular-cli#32]
I think because the "base" tag was never rebuilt, the new "6.1.2-chromium" tag is using an out of date node version.
These are the versions for 6.1.2-chromium
```
> npm -v
> 3.10.10
> node -v
> v6.11.2
```

These are the versions for 6.1.2
```
> npm -v
> 5.6.0
> node -v
> v8.11.3
```

**Comment by alejandroSuch** [comment]
Hi Garun.

I have updated the base image. Now it has the following versions:
- node: 8.11.4
- npm: 5.6.0
- yarn: 1.9.4

Next builds will use this base image.

Regards,
Alex

**Comment by alejandroSuch** [comment]
Version `6.2` is already using it
